# -*- coding: utf-8 -*-
"""lang_en.py — English UI strings. key = 中文源串(app.py 里 _() 的实参)。

占位符约定: {name} 形式的命名占位符必须在译文中原样保留(个数与名字一致)。
"""
STRINGS = {
    '无': 'None',
    '已喷涂检测(标记哪些涂装正喷在车上)通过只读扫描游戏进程内存实现:\n\n· 原理: 游戏车库表常驻内存, 工具只读匹配其中的涂装文件名记录;\n· 方式: OpenProcess + ReadProcessMemory, 不修改内存、不 hook、不附加调试器;\n· 前提: 需要游戏正在运行。\n\n风险提示: 只读外部读取不触发调试器检测, 理论风险远低于修改器,\n但不能保证绝对零风险。介意请勿使用相关开关, 或仅在离线模式下使用。': 'Applied-livery detection (marks which liveries are currently applied to cars) works by read-only scanning of the game process memory:\n\n· How it works: the game keeps its garage table in memory; the tool only matches livery file name records in it, read-only.\n· Method: OpenProcess + ReadProcessMemory. It does not modify memory, hook anything, or attach a debugger.\n· Requirement: the game must be running.\n\nRisk notice: read-only external reads do not trigger debugger detection; the theoretical risk is far lower than that of trainers,\nbut absolute zero risk cannot be guaranteed. If this concerns you, do not use the related switches, or use them only in offline mode.',
    '下载日期(新→旧)': 'Download date (new→old)',
    '下载日期(旧→新)': 'Download date (old→new)',
    '名称': 'Name',
    '车型': 'Model',
    '作者': 'Creator',
    '车厂': 'Brand',
    '游戏内顺序': 'In-game order',
    '同车微调(v1/v2)': 'Same-car tweak (v1/v2)',
    '同车型+同作者, 图片距离≤10 且名称相似度≥0.6': 'Same model + same creator, image distance ≤10 and name similarity ≥0.6',
    '跨车型移植': 'Cross-model port',
    '不同车型+同作者, 图片距离≤6 且名称相似度≥0.6': 'Different models + same creator, image distance ≤6 and name similarity ≥0.6',
    '同名异版': 'Same name, different version',
    '车型/名称/作者相同而创建时间不同——疑似版本迭代': 'Same model/name/creator but different creation time — likely version iterations',
    '多次下载': 'Downloaded multiple times',
    '车型/名称/作者/创建时间全同而下载时间不同——真重复副本, 可任选保留': 'Identical model/name/creator/creation time but different download time — true duplicate copies; keep any one',
    '(自定义)': '(Custom)',
    'FH6 涂装查看器': 'FH6 Livery Viewer',
    '未选择条目': 'No item selected',
    '已清除快筛': 'Quick filter cleared',
    '商店版/pgs': 'Store/pgs',
    '重复检测参数': 'Duplicate Detection Parameters',
    '任意': 'Any',
    '相同': 'Same',
    '不同': 'Different',
    '不参与': 'Not used',
    '不比对': "Don't compare",
    '距离≤N': 'Distance ≤N',
    '任一方无图': 'Either has no image',
    '≥X(找相似名)': '≥X (find similar names)',
    '<X(找不同名)': '<X (find different names)',
    '车型:': 'Model:',
    '条目文件名里的车型 ID': 'Model ID in the item file name',
    '作者:': 'Creator:',
    '涂装作者; Forza 默认名视为匿名, 匿名不参与相同/不同判定': 'Livery creator; Forza default names count as anonymous, and anonymous entries are excluded from same/different checks',
    '创建时间:': 'Created:',
    '文件名时间戳(≈作者创作时间); 任一方缺失则条件不成立': "File name timestamp (≈ author's creation time); condition fails if either side lacks it",
    '下载时间:': 'Downloaded:',
    '文件 mtime(≈玩家下载落盘时间); 任一方缺失则条件不成立': 'File mtime (≈ when the player downloaded it); condition fails if either side lacks it',
    '手动': 'Manual',
    '重复涂装分析中(解码缩略图计算哈希)…': 'Analyzing duplicate liveries (decoding thumbnails to compute hashes)…',
    '已喷在车上 ✓': 'Applied to a car ✓',
    '未喷在车上': 'Not applied to a car',
    '已喷涂检测: 只读扫描游戏内存中…': 'Applied detection: scanning game memory (read-only)…',
    '设置': 'Settings',
    '自动定位已取消': 'Auto-locate cancelled',
    '刷新': 'Refresh',
    '手动选择目录…': 'Choose Folder Manually…',
    '备份整个存档': 'Back Up Entire Save',
    '打开存档目录': 'Open Save Folder',
    '全部车厂': 'All brands',
    '涂装筛选': 'Livery Filters',
    '仅显示重复涂装(不限场景)': 'Show duplicate liveries only (any scenario)',
    '仅显示多涂装车型(≥2 种)': 'Show only models with multiple liveries (≥2)',
    '仅显示单涂装车型(仅 1 种)': 'Show only models with a single livery (just 1)',
    '仅显示已喷涂(在车上)': 'Show applied only (on a car)',
    '仅显示未喷涂(不在车上)': 'Show unapplied only (not on a car)',
    '(无预览)': '(No preview)',
    '查看大图': 'View Large Image',
    '自动定位到游戏': 'Auto-Locate in Game',
    '所在文件夹': 'Open Containing Folder',
    '就绪': 'Ready',
    '只显示该车型': 'Show This Model Only',
    '只显示该作者': 'Show This Creator Only',
    '查看缩略图': 'View Thumbnail',
    '定位到涂装位置': 'Locate Livery Position',
    '复制名称': 'Copy Name',
    '复制车型': 'Copy Model',
    '复制作者': 'Copy Creator',
    '仅重复': 'Duplicates only',
    '多涂装车型': 'Multi-livery models',
    '单涂装车型': 'Single-livery models',
    '仅已喷涂': 'Applied only',
    '仅未喷涂': 'Unapplied only',
    '快筛': 'quick filter',
    '未找到 FH6 存档, 请用「手动选择目录」指定存档文件夹': 'No FH6 save found. Use "Choose Folder Manually" to specify the save folder.',
    '选择 FH6 存档目录(remote 或 ContainersRoot)': 'Select FH6 save folder (remote or ContainersRoot)',
    '已喷涂检测: 未检测到游戏进程 (游戏启动后可重试)': 'Applied detection: game process not found (retry after the game starts)',
    '检测喷涂状态': 'Detect Applied Status',
    '预览': 'Preview',
    '该条目没有预览图': 'This item has no preview image',
    '未检测到游戏进程。\n已喷涂检测需要游戏正在运行, 请启动游戏后重试。': 'Game process not found.\nApplied-livery detection requires the game to be running. Launch the game and try again.',
    '该涂装没有游戏内位置信息': 'This livery has no in-game position info',
    '请先在左侧选中一个涂装': 'Select a livery on the left first',
    '自动定位': 'Auto-Locate',
    '该涂装就在 1行1列, 无需按键': 'This livery is already at Row 1, Col 1; no keys needed',
    '未找到游戏窗口, 请先打开游戏': 'Game window not found. Launch the game first.',
    '无法切换到游戏窗口, 已取消': 'Could not switch to the game window; cancelled',
    '复制': 'Copy',
    '全选': 'Select All',
    '复制全部': 'Copy All',
    '备份完成': 'Backup Complete',
    '{name} — 预览(滚轮缩放, 拖动平移)': '{name} — Preview (wheel to zoom, drag to pan)',
    '其他': 'Other',
    'ID {id}  {date}': 'ID {id}  {date}',
    '作者 {name}': 'Creator {name}',
    '快筛: 只显示{desc} (右键菜单可清除)': 'Quick filter: showing only {desc} (clear via right-click menu)',
    '清除快筛': 'Clear Quick Filter',
    '复制游戏内位置': 'Copy In-Game Position',
    '共 {n} 个条目, 显示 {m} 个': 'Total {n} items, showing {m}',
    '已识别车型 {n} 个': '{n} models recognized',
    '{x}行{y}列': 'Row {x}, Col {y}',
    '检测到存档更新: +{new} 新增 / -{gone} 删除, 已刷新': 'Save update detected: +{new} added / -{gone} removed, refreshed',
    '自动刷新: 存档目录不可访问, 已暂停': 'Auto-refresh: save directory not accessible, paused',
    '自动刷新: 存档目录已恢复': 'Auto-refresh: save directory accessible again',
    '自动刷新失败, 已等待重试': 'Auto-refresh failed, will retry',
    '自动刷新: 已重新解析 {n} 个条目': 'Auto-refresh: re-parsed {n} entries',
    '出厂默认条件': 'Factory default condition',
    '已喷涂检测: {n} 个涂装正在车上': 'Applied detection: {n} liveries currently on cars',
    'ID {id}': 'ID {id}',
    '(无预览图)': '(No preview image)',
    '名称: {name}': 'Name: {name}',
    '车型: {car}': 'Model: {car}',
    '作者: {creator}': 'Creator: {creator}',
    '日期: {ts}': 'Date: {ts}',
    '状态: {status}': 'Status: {status}',
    '大小: {size}': 'Size: {size}',
    '文件: {base}': 'File: {base}',
    '已复制: {text}': 'Copied: {text}',
    '确认开始检测？': 'Start detection now?',
    '取值范围 0~2000 毫秒': 'Value must be within 0~2000 ms',
    '备份失败': 'Backup Failed',
    '放大 (+)': 'Zoom In (+)',
    '缩小 (−)': 'Zoom Out (−)',
    '原始尺寸': 'Original Size',
    '适应窗口': 'Fit to Window',
    'FH6 存档:': 'FH6 Save:',
    '置顶': 'Always on Top',
    '自动刷新': 'Auto Refresh',
    '⚠ 检测喷涂状态': '⚠ Detect Applied Status',
    '搜索:': 'Search:',
    '车厂:': 'Brand:',
    '排序:': 'Sort:',
    '次选:': 'Then by:',
    '分组:': 'Group:',
    '更新链接: {url}': 'Update link: {url}',
    '本工具与 Microsoft、Xbox、Playground Games、Turn 10 无关，Forza 相关商标归其各自所有者。\n工具仅读取本地内容，不提供任何修改、解锁或联机功能。\n使用本工具产生的任何后果由使用者自行承担。\n': 'This tool is not affiliated with Microsoft, Xbox, Playground Games, or Turn 10; Forza-related trademarks belong to their respective owners.\nThe tool only reads local content and provides no modification, unlock, or online features.\nYou assume all consequences of using this tool.\n',
    '(未解析)': '(Unparsed)',
    '加载中…': 'Loading…',
    '车型 {name}': 'Model {name}',
    '车型 ID {id}': 'Model ID {id}',
    '已上车 {n}': 'On cars: {n}',
    '重复 {g} 组({f} 个)': 'Duplicates: {g} groups ({f} items)',
    '[{src}]  用户 {user}  |  {dir}': '[{src}]  User {user}  |  {dir}',
    '模板:': 'Template:',
    '图片:': 'Image:',
    '感知哈希汉明距离 0~64, 越小要求越像;「任一方无图」=其中一条没有预览图文件(解码失败不算)': 'dHash Hamming distance 0~64; smaller means more alike. "Either has no image" = one of them has no preview image file (decode failures do not count)',
    '名称相似度:': 'Name similarity:',
    'difflib 相似度 0~1; 任一方名称为空按 0 处理': 'difflib similarity 0~1; an empty name on either side counts as 0',
    '当前应用的条件': 'Currently applied condition',
    '判定方式: 两两配对, 同时满足以上启用条件的两条涂装判为重复;并按传递关系合并成组(A~B、B~C ⇒ 三者同组)。条件越宽松组越大。改动仅本次运行有效。': 'How it works: pairwise comparison; two liveries that satisfy all enabled conditions above are judged duplicates, and matches are merged transitively into groups (A~B and B~C ⇒ all three share a group). Looser conditions make larger groups. Changes apply to this run only.',
    '阈值无效: 距离 0~64 / 相似度 0.00~1.00': 'Invalid threshold: distance 0~64 / similarity 0.00~1.00',
    '恢复默认': 'Restore Defaults',
    '确定': 'OK',
    '取消': 'Cancel',
    '已喷涂检测失败: {err}': 'Applied detection failed: {err}',
    '已标记喷涂\n\n{n} 个涂装正喷在车上, 已用喷漆角标标出。': 'Applied liveries marked\n\n{n} liveries are currently on cars and have been marked with a spray-can badge.',
    '游戏内位置: {pos} (共 {total} 列)': 'In-game position: {pos} ({total} columns total)',
    '按键路径: {path}': 'Key path: {path}',
    '已分享': 'Shared',
    '本地': 'Local',
    '喷涂状态: {status}': 'Applied status: {status}',
    '重复: 第 {gid} 组, 共 {n} 个相同涂装': 'Duplicate: group {gid}, {n} identical liveries in total',
    '层数: {n}': 'Layers: {n}',
    '注意: header 内嵌车型 ID {id} 与文件名不一致': 'Note: model ID {id} embedded in the header differs from the file name',
    '描述: {desc}': 'Description: {desc}',
    '自动定位按键节奏 (毫秒, 周期 = 保持 + 间隔):': 'Auto-locate key timing (ms; cycle = hold + gap):',
    '按下保持:': 'Key hold:',
    '键间间隔:': 'Key gap:',
    '(仅本次运行有效)': '(this run only)',
    '请输入整数毫秒值': 'Enter an integer value in milliseconds',
    '按键节奏: 保持 {hold}ms + 间隔 {gap}ms (本次运行有效)': 'Key timing: hold {hold}ms + gap {gap}ms (this run only)',
    '自动定位完成: {path}': 'Auto-locate finished: {path}',
    '已备份整个存档目录到:\n{out}': 'Entire save folder backed up to:\n{out}',
    '备份完成: {out}': 'Backup complete: {out}',
    '无法加载预览图(需要 Pillow)': 'Cannot load preview image (Pillow required)',
    '{name} · {n} 个': '{name} · {n} items',
    '其他 · {n} 个': 'Other · {n} items',
    '复制游戏内位置 ({pos})': 'Copy In-Game Position ({pos})',
    '涂装筛选: {p}': 'Livery Filters: {p}',
    '重复检测条件已更新: {hit} 个条目在重复组里, 共 {grp} 组': 'Duplicate detection condition updated: {hit} items in duplicate groups, {grp} groups in total',
    '读取失败': 'Read failed',
    '检测失败: {err}': 'Detection failed: {err}',
    '无需按键(就在 1行1列)': 'No keys needed (already at Row 1, Col 1)',
    'FH6 涂装查看器 v{v}': 'FH6 Livery Viewer v{v}',
    '第 {gid} 组 · {n} 个': 'Group {gid} · {n} items',
}
